name: PowerNBT
description: Powerful nbt editor for bukkit server
author: DPOH-VAR
main: me.dpohvar.powernbt.PowerNBT
version: 0.4.0
commands:
    nbt:
        description: use nbt commands
        usage: /nbt {object} [query] [{operand} [{object} [query]]]
        permission: powernbt.use
















