debug: ${plugin-debug}
lang: system
editor:
  enabled: false
  icons:
    buttons:
      control:
        update: "⟳"
        remove: "❌"
        selectJson: "#"
        copyToBuffer: "↑"
        pasteFromBuffer: "↓"
        copyToClipboard: "C"
        edit: "✎"
    paginator:
      prev: "<"
      prevActive: "<"
      next: ">"
      nextActive: ">"
    lineTopSeparator: "███████████████████████████████████"
    lineBottomSeparator: "███████████████████████████████████"
  colors:
    lineTopSeparator: "#aabbaa"
    lineBottomSeparator: "#aabbaa"
    etc: "#996633"
    buttons:
      bar: "dark_gray"
      control:
        update: "green"
        remove: "red"
        selectJson: "yellow"
        copyToBuffer: "blue"
        pasteFromBuffer: "light_purple"
        copyToClipboard: "aqua"
        edit: "gold"
    paginator:
      errorText: "dark_red"
      text: "gray"
      nav: "dark_gray"
      navActive: "aqua"
    breadcrumbs:
      root: "#bbffcc"
      delimiter: "#888888"
      steps:
      - "#ddff00"
      - "#ffcc22"
    disabledBreadcrumbs:
      root: "#cccccc"
      query: "#bbbbbb"
      delimiter: "#888888"
    types:
      null: "#666677"
      bool: "#ffaa44"
      char: "#aadd88"
      byte: "#ff8888"
      short: "#ffff88"
      int: "#99bbff"
      long: "#99ffff"
      float: "#dd88ff"
      double: "#ffaaff"
      byte[]: "#bb6666"
      int[]: "#6699bb"
      long[]: "#77bbbb"
      map: "#77cc33"
      string: "#66ff66"
      list: "#6677bb"
      unknown: "#ff44ff"

ignore_set:
  block:
  - id
  - x
  - y
  - z
  entity:
  - id
  - UUID
  - UUIDMost
  - UUIDLeast
  - WorldUUIDLeast
  - WorldUUIDMost

hooks:
  default:
    entity:
      getNBT: "net.minecraft.world.entity.Entity d(net.minecraft.nbt.NBTTagCompound): boolean"
      getNBTSimple: "net.minecraft.world.entity.Entity save(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.entity.Entity load(net.minecraft.nbt.NBTTagCompound): void"
      getHandle: "{cb}.entity.CraftEntity *(): net.minecraft.world.entity.Entity"
      createType: "net.minecraft.world.entity.EntityTypes public static *(net.minecraft.nbt.NBTTagCompound, net.minecraft.world.level.World): java.util.Optional"
      getBukkitEntity: "net.minecraft.world.entity.Entity *(): {cb}.entity.CraftEntity"
    block:
      getSnapshot: "{cb}.block.CraftBlockEntityState getSnapshot()"
      getNBT: "net.minecraft.world.level.block.entity.TileEntity save(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.level.block.entity.TileEntity load(net.minecraft.nbt.NBTTagCompound): void"
    item:
      handle: "{cb}.inventory.CraftItemStack *:net.minecraft.world.item.ItemStack"
      craftCopy: "{cb}.inventory.CraftItemStack static *(org.bukkit.inventory.ItemStack): {cb}.inventory.CraftItemStack"
      getNBT: "net.minecraft.world.item.ItemStack *(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.item.ItemStack declared load(net.minecraft.nbt.NBTTagCompound): void"
    world:
      getHandle: "{cb}.CraftWorld *(): net.minecraft.server.level.WorldServer"
      addEntity: "net.minecraft.server.level.WorldServer addEntity(net.minecraft.world.entity.Entity, org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason): boolean"
  1_18_1-R0_1-SNAPSHOT:
    entity:
      getNBT: "net.minecraft.world.entity.Entity d(net.minecraft.nbt.NBTTagCompound): boolean"
      getNBTSimple: "net.minecraft.world.entity.Entity f(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.entity.Entity g(net.minecraft.nbt.NBTTagCompound): void"
      getHandle: "{cb}.entity.CraftEntity *(): net.minecraft.world.entity.Entity"
      createType: "net.minecraft.world.entity.EntityTypes public static *(net.minecraft.nbt.NBTTagCompound, net.minecraft.world.level.World): java.util.Optional"
      getBukkitEntity: "net.minecraft.world.entity.Entity *(): {cb}.entity.CraftEntity"
    block:
      getSnapshot: "{cb}.block.CraftBlockEntityState getSnapshot()"
      getNBT: "net.minecraft.world.level.block.entity.TileEntity m(): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.level.block.entity.TileEntity a(net.minecraft.nbt.NBTTagCompound): void"
    item:
      handle: "{cb}.inventory.CraftItemStack *:net.minecraft.world.item.ItemStack"
      craftCopy: "{cb}.inventory.CraftItemStack static *(org.bukkit.inventory.ItemStack): {cb}.inventory.CraftItemStack"
      getNBT: "net.minecraft.world.item.ItemStack *(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.item.ItemStack declared load(net.minecraft.nbt.NBTTagCompound): void"
    world:
      getHandle: "{cb}.CraftWorld *(): net.minecraft.server.level.WorldServer"
      addEntity: "net.minecraft.server.level.WorldServer addEntity(net.minecraft.world.entity.Entity, org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason): boolean"
