debug: false
lang: system
ignore_get:
  entity:
  - UUIDMost
  - UUIDLeast
  - WorldUUIDLeast
  - WorldUUIDMost
ignore_set:
  block:
  - id
  - x
  - y
  - z
  entity:
  - UUIDMost
  - UUIDLeast
  - WorldUUIDLeast
  - WorldUUIDMost