debug: ${plugin-debug}
lang: system
ignore_set:
  block:
  - id
  - x
  - y
  - z
  entity:
  - UUIDMost
  - UUIDLeast
  - WorldUUIDLeast
  - WorldUUIDMost

hooks:
  1_18_1-R0_1-SNAPSHOT:
    entity:
      getNBT: "net.minecraft.world.entity.Entity *(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.entity.Entity b(net.minecraft.nbt.NBTTagCompound): void"
      getHandle: "{cb}.entity.CraftEntity *(): net.minecraft.server.level.EntityPlayer"
      createType: "net.minecraft.world.entity.EntityTypes static *(net.minecraft.nbt.NBTTagCompound, net.minecraft.world.level.World): java.util.Optional"
      getBukkitEntity: "net.minecraft.world.entity.Entity *(): {cb}.entity.CraftEntity"
    block:
      getSnapshot: "{cb}.block.CraftBlockEntityState getSnapshot()"
      getNBT: "net.minecraft.world.level.block.entity.TileEntity m(): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.level.block.entity.TileEntity a(net.minecraft.nbt.NBTTagCompound): void"
    item:
      handle: "{cb}.inventory.CraftItemStack *:net.minecraft.world.item.ItemStack"
      craftCopy: "{cb}.inventory.CraftItemStack static *(org.bukkit.inventory.ItemStack): {cb}.inventory.CraftItemStack"
      getNBT: "net.minecraft.world.item.ItemStack *(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.item.ItemStack *(net.minecraft.nbt.NBTTagCompound): void"
    world:
      getHandle: "{cb}.CraftWorld *(): net.minecraft.server.level.WorldServer"
      addEntity: "net.minecraft.server.level.WorldServer *(net.minecraft.world.entity.Entity, org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason): boolean"
