name: PowerNBT
description: Powerful nbt editor for bukkit and MCPC+
author: DPOH-VAR
main: me.dpohvar.powernbt.PowerNBT
website: http://dev.bukkit.org/bukkit-plugins/varscript/
version: 0.7.2
commands:
    powernbt:
        description: use nbt commands
        usage: /nbt ... use [Tab] key for help
        permission: powernbt.use
        aliases:
            - pnbt
            - nbt