name: ${artifactId}
description: ${plugin-description}
author: ${plugin-author}
main: me.dpohvar.powernbt.PowerNBT
website: http://dev.bukkit.org/bukkit-plugins/varscript/
version: ${plugin-version}
commands:
    powernbt:
        description: use nbt commands
        usage: /nbt ... use [Tab] key for help
        permission: powernbt.use
        aliases:
            - pnbt
            - nbt