name: PowerNBT
description: Powerful nbt editor for bukkit and MCPC+
author: DPOH-VAR
main: me.dpohvar.powernbt.PowerNBT
version: 0.6.2
commands:
    powernbt:
        description: use nbt commands
        usage: /nbt ... use [Tab] key for help
        permission: powernbt.use
        aliases:
            - pnbt
            - nbt